// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmuuysgkwdzerdaqbayu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdXV5c2drd2R6ZXJkYXFiYXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1Njk1NjksImV4cCI6MjA1MTE0NTU2OX0.j4HXIdI2gdjmWU7qzgjbZuCht0cESnNiF_IZahTPVng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);